// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ibQ9jg9UpBZxbFHw-pgAQF4bajSzl-Y',
    appId: '1:890796736503:web:988dd33d31ffd43133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    authDomain: 'family-meet-c4b80.firebaseapp.com',
    databaseURL:
        'https://family-meet-c4b80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'family-meet-c4b80.appspot.com',
    measurementId: 'G-YTZ884V5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDMFsPvWL7nUwl8G6m6n4zimfz3lUj_o',
    appId: '1:890796736503:android:69c17e0c4351238333f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    databaseURL:
        'https://family-meet-c4b80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'family-meet-c4b80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUS0LEj6CLzyrwXa8tQY1CzZjP-JPCVU',
    appId: '1:890796736503:ios:9e37b0dd7da36a2133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    databaseURL:
        'https://family-meet-c4b80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'family-meet-c4b80.appspot.com',
    iosClientId:
        '890796736503-5bqpu03u6pbnaftk6vijhk0ovhedfq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAppli1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUS0LEj6CLzyrwXa8tQY1CzZjP-JPCVU',
    appId: '1:890796736503:ios:9e37b0dd7da36a2133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    databaseURL:
        'https://family-meet-c4b80-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'family-meet-c4b80.appspot.com',
    iosClientId:
        '890796736503-5bqpu03u6pbnaftk6vijhk0ovhedfq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAppli1',
  );
}
/*aga
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ibQ9jg9UpBZxbFHw-pgAQF4bajSzl-Y',
    appId: '1:890796736503:web:988dd33d31ffd43133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    authDomain: 'family-meet-c4b80.firebaseapp.com',
    storageBucket: 'family-meet-c4b80.appspot.com',
    measurementId: 'G-YTZ884V5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDMFsPvWL7nUwl8G6m6n4zimfz3lUj_o',
    appId: '1:890796736503:android:69c17e0c4351238333f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    storageBucket: 'family-meet-c4b80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUS0LEj6CLzyrwXa8tQY1CzZjP-JPCVU',
    appId: '1:890796736503:ios:9e37b0dd7da36a2133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    storageBucket: 'family-meet-c4b80.appspot.com',
    iosClientId: '890796736503-5bqpu03u6pbnaftk6vijhk0ovhedfq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAppli1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUS0LEj6CLzyrwXa8tQY1CzZjP-JPCVU',
    appId: '1:890796736503:ios:9e37b0dd7da36a2133f8f2',
    messagingSenderId: '890796736503',
    projectId: 'family-meet-c4b80',
    storageBucket: 'family-meet-c4b80.appspot.com',
    iosClientId: '890796736503-5bqpu03u6pbnaftk6vijhk0ovhedfq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAppli1',
  );
}

*/